[package]
name = "rts"
version = "0.1.0"
authors = ["Jerahmeel Cosinas <me@jerahmeelcosinas.net>"]
edition = "2018"

[dependencies]
bevy = "0.5"
bevy_egui = "0.6"

[dev-dependencies]
proptest = "0.10.1"
